image: node:12-alpine

# Cache node modules - speeds up future builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

# Define the stages
stages:
  - setup
  - build
  - test
  - deploy

# Define the process for each stage

# Define the process for setup stage
setup:
  stage: setup
  tags:
    - ohtu-build-1
  script:
    - npm install

# Define the process for build stage
build:
  stage: build
  tags:
    - ohtu-build-1
  script:
    - npm run build

# Define the process for test stage
test:
  stage: test
  tags:
    - ohtu-build-1
  script:
    - npm run coverage
  coverage: /All files\s*\|\s*([\d\.]+)/

# Define the process for deploy stage to development environment
deploy_dev:
  stage: deploy
  tags:
    - ohtu-build-1
  environment:
    name: lataamo-403
  only:
    - master
  script:
    - echo "====== Deploy to development server ========"
    - echo "====== Install rsync and openssh ========="
    - apk add --no-cache rsync openssh
    - echo "====== Activate the ssh-agent ========"
    - eval $(ssh-agent -s)
    - echo "======= Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store ====="
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "====== Add target servers secret key ======"
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY  >> ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - echo "====== Test ssh connection and make api folder if not exist ======"
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T lataamo@lataamo-dev.it.helsinki.fi "mkdir -p /home/lataamo/proxy"
    - echo "====== Sync local and remote directory ======"
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -azPq -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --exclude=".env" --exclude="/api/uploads" --exclude="/logs" --exclude="/files" --delete ./ lataamo@lataamo-dev.it.helsinki.fi:/home/lataamo/proxy
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T lataamo@lataamo-dev.it.helsinki.fi "pm2 restart app"

# Define the process for deploy stage to test environment
deploy_test:
  stage: deploy
  tags:
    - ohtu-build-1
  environment:
    name: test
  only:
    - test
  script:
    - echo "====== Deploy to test server ========"
    - echo "====== Install rsync and openssh ========="
    - apk add --no-cache rsync openssh
    - echo "====== Activate the ssh-agent ========"
    - eval $(ssh-agent -s)
    - echo "======= Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store ====="
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "====== Add target servers secret key ======"
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY  >> ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - echo "====== Test ssh connection and make api folder if not exist ======"
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T lataamo@lataamo-test.it.helsinki.fi "mkdir -p /home/lataamo/proxy"
    - echo "====== Sync local and remote directory ======"
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -azPq -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --exclude=".env" --exclude="/api/uploads" --exclude="/logs" --exclude="/files"  --delete ./ lataamo@lataamo-test.it.helsinki.fi:/home/lataamo/proxy
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T lataamo@lataamo-test.it.helsinki.fi "pm2 restart app"

# Define the process for deploy stage to test environment
deploy_prod:
  stage: deploy
  tags:
    - ohtu-build-1
  environment:
    name: prod
  only:
    - prod
  when: manual
  script:
    - echo "====== Deploy to production server ========"
    - echo "====== Install rsync and openssh ========="
    - apk add --no-cache rsync openssh
    - echo "====== Activate the ssh-agent ========"
    - eval $(ssh-agent -s)
    - echo "======= Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store ====="
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "====== Add target servers secret key ======"
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY  >> ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - echo "====== Test ssh connection and make api folder if not exist ======"
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T lataamo@lataamo-prod.it.helsinki.fi "mkdir -p /home/lataamo/proxy"
    - echo "====== Sync local and remote directory ======"
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -azPq -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --exclude=".env" --exclude="/api/uploads" --exclude="/logs" --exclude="/files"  --delete ./ lataamo@lataamo-prod.it.helsinki.fi:/home/lataamo/proxy
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T lataamo@lataamo-prod.it.helsinki.fi "NODE_ENV=production pm2 restart app"
