image: node:8-alpine

# Cache node modules - speeds up future builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

# Define the stages
stages:
  - setup
  - build
  - deploy

# Define the process for each stage

# Define the process for setup stage
setup:
  stage: setup
  script:
    - npm install

# Define the process for build stage
build:
  stage: build
  script:
    - npm run build

# Define the process for deploy stage to development environment
deploy_dev:
  stage: deploy
  environment:
    name: development
  only:
    - master
  script:
    - echo "====== Deploy to development server ========"
